#
# Copyright (C) 2025 AuxXxilium <https://github.com/AuxXxilium>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build LKMs with Docker

on:  
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: false
        type: string
      latest:
        description: "latest"
        default: true
        type: boolean
      prerelease:
        description: "pre release"
        default: false
        type: boolean

jobs:
  build:
    strategy:
      matrix:
        version: ${{ fromJSON(inputs.version != '' && format('["{0}"]', inputs.version) || '["7.2", "7.3", "7.4"]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init Env
        run: |
          git config --global user.email "info@auxxxilium.tech"
          git config --global user.name "AuxXxilium"
          sudo timedatectl set-timezone "Europe/Berlin"

      - name: Build LKMs
        run: |
          chmod +x ./build-lkm.sh
          ./build-lkm.sh -v ${{ matrix.version }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rp-lkms-${{ matrix.version }}
          path: |
            ${{ github.workspace }}/releases/*

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/rp-lkms

      - name: Calculate Version
        run: |
          # Calculate Version
          VERSION=""
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="`date +'%y.%m.%d'`"
          fi

          if [ -n "${VERSION}" ]; then
            echo "Version: ${VERSION}"
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
          fi

      - name: Prepare Release
        if: env.VERSION != ''
        run: |
          # Update VERSION file with release version
          echo "${{ env.VERSION }}" > ${{ github.workspace }}/rp-lkms/VERSION

      - name: Create Release Zip
        if: env.VERSION != ''
        run: |
          cd ${{ github.workspace }}/rp-lkms
          rm -f ../rp-lkms.zip
          find . -type f -name "*.gz" -print0 | xargs -0 -r zip -j9 ../rp-lkms.zip
          zip -j9 ../rp-lkms.zip VERSION
          ls -lh ${{ github.workspace }}/rp-lkms.zip

      - name: Release
        if: success() && env.VERSION != ''
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          makeLatest: ${{ inputs.latest }}
          prerelease: ${{ inputs.prerelease }}
          allowUpdates: true
          artifacts: |
            ${{ github.workspace }}/rp-lkms.zip