#
# Copyright (C) 2025 AuxXxilium <https://github.com/AuxXxilium>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build LKMs with Docker

on:  
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: false
        type: string
      latest:
        description: "latest"
        default: true
        type: boolean
      prerelease:
        description: "pre release"
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init Env
        run: |
          git config --global user.email "info@auxxxilium.tech"
          git config --global user.name "AuxXxilium"
          sudo timedatectl set-timezone "Europe/Berlin"

      - name: Build LKMs
        run: |
          chmod +x ./build-lkm.sh
          ./build-lkm.sh --all

      - name: Calculate Version
        run: |
          # Calculate Version
          VERSION=""
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          else
            LATEST_TAG="$(curl -skL "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name" 2>/dev/null)"
            if [[ -n "${LATEST_TAG}" && "`echo ${LATEST_TAG} | cut -d '.' -f 1,2,3`" = "`date +'%y.%m.%d'`" ]]; then
              VERSION="`echo ${LATEST_TAG} | awk -F '.' '{$4=$4+1}1' OFS='.'`"
            else
              VERSION="`date +'%y.%m.%d'`"
            fi
          fi

          if [ -n "${VERSION}" ]; then
            echo "Version: ${VERSION}"
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
          fi

      - name: Prepare Release
        if: env.VERSION != ''
        run: |
          # Update VERSION file with release version
          echo "${{ env.VERSION }}" > releases/VERSION

      - name: Create Release Zip
        if: env.VERSION != ''
        run: |
          cd releases
          zip -j9 ../rp-lkms.zip *
          ls -lh ../rp-lkms.zip

      - name: Release
        if: success() && env.VERSION != ''
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          makeLatest: ${{ inputs.latest }}
          prerelease: ${{ inputs.prerelease }}
          allowUpdates: true
          artifacts: |
            ${{ github.workspace }}/rp-lkms.zip